//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    
    public enum AvailabityStatusEnum : int
    {
        Active_Undergraduate = 1,
        Disabled = 2,
        Sick = 3,
        Leave = 4,
        Deceased = 5,
        Withdrawn = 6,
        Graduated = 7,
        Active_Spill = 8
    }
}
