//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curriculum
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public int RequirementId { get; set; }
        public int ProgrammeLevelId { get; set; }
    
        public virtual Requirement Requirement { get; set; }
        public virtual ProgrammeLevel ProgrammeLevel { get; set; }
    }
}
