//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    
    public enum StudentLevelPaymentStatusEnum : int
    {
        Full_Payment_Outstanding = 1,
        Part_Payment_Paid = 2,
        Balance_Payment_Outstanding = 3,
        Full_Payment_Paid = 4,
        Late_Payment_Outstanding = 5,
        Late_Payment_Paid = 6,
        Other_Payment_Outstanding = 7,
        Other_Payment_Paid = 8
    }
}
