//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Student()
        {
            this.StudentLevels = new HashSet<StudentLevel>();
        }
    
        public int Id { get; set; }
        public string MatricNo { get; set; }
        public string Surname { get; set; }
        public string Othername { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string StateofOrigin { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<int> YearofAdmission { get; set; }
        public string ModeofAdmission { get; set; }
        public string NameofNextofKin { get; set; }
        public string PhoneNoNextofKin { get; set; }
        public string Relationship { get; set; }
        public Nullable<int> ProgrammeId { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public int CentreId { get; set; }
        public int LGAId { get; set; }
        public string Picture { get; set; }
        public string Signature { get; set; }
        public System.DateTime DOB { get; set; }
        public string PlaceofBirth { get; set; }
        public string Genotype { get; set; }
        public string BloodGroup { get; set; }
    
        public virtual Programme Programme { get; set; }
        public virtual StudentStatu StudentStatu { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentLevel> StudentLevels { get; set; }
        public virtual Centre Centre { get; set; }
        public virtual LGA LGA1 { get; set; }
    }
}
