//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ResultMEntitiesxx : DbContext
    {
        public ResultMEntitiesxx()
            : base("name=ResultMEntitiesxx")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AvailabityStatu> AvailabityStatus { get; set; }
        public virtual DbSet<AwardLevel> AwardLevels { get; set; }
        public virtual DbSet<Award> Awards { get; set; }
        public virtual DbSet<Centre> Centres { get; set; }
        public virtual DbSet<City> Cities { get; set; }
        public virtual DbSet<Cours> Courses { get; set; }
        public virtual DbSet<Curriculum> Curricula { get; set; }
        public virtual DbSet<Department> Departments { get; set; }
        public virtual DbSet<DisciplinaryStatu> DisciplinaryStatus { get; set; }
        public virtual DbSet<Faculty> Faculties { get; set; }
        public virtual DbSet<GeoZone> GeoZones { get; set; }
        public virtual DbSet<Grade> Grades { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<LGA> LGAs { get; set; }
        public virtual DbSet<ProgrammeLevel> ProgrammeLevels { get; set; }
        public virtual DbSet<Programme> Programmes { get; set; }
        public virtual DbSet<ProgrammeStatu> ProgrammeStatus { get; set; }
        public virtual DbSet<Registration> Registrations { get; set; }
        public virtual DbSet<RegistrationStatu> RegistrationStatus { get; set; }
        public virtual DbSet<RequiredCours> RequiredCourses { get; set; }
        public virtual DbSet<Requirement> Requirements { get; set; }
        public virtual DbSet<Requirements_GeneralReq> Requirements_GeneralReq { get; set; }
        public virtual DbSet<Result> Results { get; set; }
        public virtual DbSet<School> Schools { get; set; }
        public virtual DbSet<Semester> Semesters { get; set; }
        public virtual DbSet<Session> Sessions { get; set; }
        public virtual DbSet<SessionSem> SessionSems { get; set; }
        public virtual DbSet<SessionStatu> SessionStatus { get; set; }
        public virtual DbSet<State> States { get; set; }
        public virtual DbSet<StudentLevelPaymentStatu> StudentLevelPaymentStatus { get; set; }
        public virtual DbSet<StudentLevel> StudentLevels { get; set; }
        public virtual DbSet<Student> Students { get; set; }
        public virtual DbSet<StudentStatu> StudentStatus { get; set; }
    }
}
