//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Registration()
        {
            this.Results = new HashSet<Result>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int RequiredCourseId { get; set; }
        public int StudentLevelId { get; set; }
        public int SessionSemId { get; set; }
        public int RegistrationStatusId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Result> Results { get; set; }
        public virtual RegistrationStatu RegistrationStatu { get; set; }
        public virtual RequiredCours RequiredCours { get; set; }
        public virtual SessionSem SessionSem { get; set; }
        public virtual StudentLevel StudentLevel { get; set; }
    }
}
