//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirements_GeneralReq
    {
        public string GenReq { get; set; }
        public int Id { get; set; }
    
        public virtual Requirement Requirement { get; set; }
    }
}
