//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requirement()
        {
            this.Curricula = new HashSet<Curriculum>();
            this.RequiredCourses = new HashSet<RequiredCours>();
        }
    
        public int Id { get; set; }
        public string Description { get; set; }
        public int MinimumUnit { get; set; }
        public int MaximumUnit { get; set; }
        public bool IsElective { get; set; }
        public int AwardLevelId { get; set; }
        public int SemesterId { get; set; }
    
        public virtual AwardLevel AwardLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Curriculum> Curricula { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequiredCours> RequiredCourses { get; set; }
        public virtual Requirements_GeneralReq Requirements_GeneralReq { get; set; }
        public virtual Semester Semester { get; set; }
        public virtual Faculty Faculty { get; set; }
        public virtual Programme Programme { get; set; }
    }
}
