//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLevel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public StudentLevel()
        {
            this.Registrations = new HashSet<Registration>();
        }
    
        public int Id { get; set; }
        public Nullable<int> StudentId { get; set; }
        public Nullable<int> ProgLevId { get; set; }
        public Nullable<int> DisciplineStatus { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<int> PayStatus { get; set; }
        public Nullable<int> AvailStatus { get; set; }
    
        public virtual AvailabityStatu AvailabityStatu { get; set; }
        public virtual DisciplinaryStatu DisciplinaryStatu { get; set; }
        public virtual ProgrammeLevel ProgrammeLevel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registration> Registrations { get; set; }
        public virtual Session Session { get; set; }
        public virtual StudentLevelPaymentStatu StudentLevelPaymentStatu { get; set; }
        public virtual Student Student { get; set; }
    }
}
