//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS.DataContract
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public class CourseDTO
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string CourseCode { get; set; }
        [DataMember]
        public string CourseTitle { get; set; }
        [DataMember]
        public Nullable<int> DeptId { get; set; }
        [DataMember]
        public Nullable<System.DateTime> DateCreated { get; set; }
    }
}
