//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS.DataContract
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public class FacultyDTO
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string FacAcronyms { get; set; }
        [DataMember]
        public Nullable<int> SchoolId { get; set; }
        [DataMember]
        public Nullable<bool> IsVisible { get; set; }
        [DataMember]
        public string FacName { get; set; }
    }
       
}
