//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS.DataContract
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int RequiredCourseId { get; set; }
        public int StudentLevelId { get; set; }
        public int SessionSemId { get; set; }
        public int RegistrationStatusId { get; set; }
    
        public virtual RequiredCourse RequiredCourse { get; set; }
        public virtual StudentLevel StudentLevel { get; set; }
        public virtual SessionSem SessionSem { get; set; }
        public virtual RegistrationStatus RegistrationStatu { get; set; }
        public virtual Result Result { get; set; }
    }
}
