//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RS.DataContract
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
    
        public int Id { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CommencementDate { get; set; }
        public Nullable<System.DateTime> NormalClosureDate { get; set; }
        public Nullable<System.DateTime> DateOpened { get; set; }
        public string OpenedBy { get; set; }
        public Nullable<System.DateTime> ClosedTime { get; set; }
        public string ClosedBy { get; set; }
        public Nullable<int> Status { get; set; }
    
      
    }
}
